/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumGroup: typeof import('./src/components/content/album-group/album-group.vue')['default']
    ArtistCard: typeof import('./src/components/content/artist-card/artist-card.vue')['default']
    ArtistCardGroup: typeof import('./src/components/content/artist-card/artist-card-group.vue')['default']
    ArtistIntroductionBrief: typeof import('./src/components/content/artist-introduction/artist-introduction-brief.vue')['default']
    ArtistIntroductionDetailed: typeof import('./src/components/content/artist-introduction/artist-introduction-detailed.vue')['default']
    Artists: typeof import('./src/components/content/artists/artists.vue')['default']
    ArtistsSimilar: typeof import('./src/components/content/artists-similar/artists-similar.vue')['default']
    Card: typeof import('./src/components/common/card/card.vue')['default']
    Card3D: typeof import('./src/components/common/card-3D/card-3D.vue')['default']
    Comment: typeof import('./src/components/content/comment/index.vue')['default']
    CommentFloor: typeof import('./src/components/content/comment/comment-floor.vue')['default']
    CommentItem: typeof import('./src/components/content/comment/comment-item.vue')['default']
    Description: typeof import('./src/components/content/description/description.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ListCard: typeof import('./src/components/content/list-card/list-card.vue')['default']
    ListCardGroup: typeof import('./src/components/content/list-card/list-card-group.vue')['default']
    Login: typeof import('./src/components/content/login/login.vue')['default']
    PlayList: typeof import('./src/components/content/playList/playList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/content/search-input/index.vue')['default']
    SongAdd2List: typeof import('./src/components/content/song-add2List/song-add2List.vue')['default']
    SongCard: typeof import('./src/components/content/song-card/song-card.vue')['default']
    SongLyric: typeof import('./src/components/content/song-lyric/song-lyric.vue')['default']
    SongLyricOld: typeof import('./src/components/content/song-lyric/song-lyric-old.vue')['default']
    SongTableCommon: typeof import('./src/components/content/songs-table/song-table-common.vue')['default']
    SongTableMy: typeof import('./src/components/content/songs-table/song-table-my.vue')['default']
    Suggestions: typeof import('./src/components/content/search-input/suggestions.vue')['default']
    SvgIcon: typeof import('./src/components/common/svg-icon/index.vue')['default']
    VideoCard: typeof import('./src/components/content/video/video-card.vue')['default']
    VideoCardGroup: typeof import('./src/components/content/video/video-card-group.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
